# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zynthian_emubox.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ZynthianEmubox(object):
    def setupUi(self, ZynthianEmubox):
        ZynthianEmubox.setObjectName(_fromUtf8("ZynthianEmubox"))
        ZynthianEmubox.resize(581, 310)
        ZynthianEmubox.setStyleSheet(_fromUtf8("background-color: rgb(35, 31, 32);"))
        self.gridLayoutWidget = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 91, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_R1 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_R1.setObjectName(_fromUtf8("gridLayout_R1"))
        self.rencoder_1 = QtGui.QDial(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 229, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.rencoder_1.setPalette(palette)
        self.rencoder_1.setStyleSheet(_fromUtf8("background-color: rgb(185, 12, 15)"))
        self.rencoder_1.setMaximum(127)
        self.rencoder_1.setTracking(True)
        self.rencoder_1.setWrapping(True)
        self.rencoder_1.setNotchTarget(3.7)
        self.rencoder_1.setObjectName(_fromUtf8("rencoder_1"))
        self.gridLayout_R1.addWidget(self.rencoder_1, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(120, 30, 341, 261))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_screen = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_screen.setObjectName(_fromUtf8("gridLayout_screen"))
        self.frame_screen = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frame_screen.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_screen.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_screen.setObjectName(_fromUtf8("frame_screen"))
        self.gridLayout_screen.addWidget(self.frame_screen, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 160, 91, 91))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_R2 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_R2.setObjectName(_fromUtf8("gridLayout_R2"))
        self.rencoder_2 = QtGui.QDial(self.gridLayoutWidget_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 229, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.rencoder_2.setPalette(palette)
        self.rencoder_2.setStyleSheet(_fromUtf8("background-color: rgb(185, 12, 15)"))
        self.rencoder_2.setMaximum(127)
        self.rencoder_2.setWrapping(True)
        self.rencoder_2.setNotchesVisible(False)
        self.rencoder_2.setObjectName(_fromUtf8("rencoder_2"))
        self.gridLayout_R2.addWidget(self.rencoder_2, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 120, 91, 36))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_B1 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_B1.setObjectName(_fromUtf8("gridLayout_B1"))
        self.switch_1 = QtGui.QPushButton(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_1.sizePolicy().hasHeightForWidth())
        self.switch_1.setSizePolicy(sizePolicy)
        self.switch_1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.switch_1.setFont(font)
        self.switch_1.setStyleSheet(_fromUtf8("background-color: rgb(60, 96, 255);\n"
"color: rgb(255, 255, 255);"))
        self.switch_1.setIconSize(QtCore.QSize(64, 64))
        self.switch_1.setFlat(False)
        self.switch_1.setObjectName(_fromUtf8("switch_1"))
        self.gridLayout_B1.addWidget(self.switch_1, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 260, 91, 36))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_B2 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_B2.setObjectName(_fromUtf8("gridLayout_B2"))
        self.switch_2 = QtGui.QPushButton(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_2.sizePolicy().hasHeightForWidth())
        self.switch_2.setSizePolicy(sizePolicy)
        self.switch_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.switch_2.setFont(font)
        self.switch_2.setStyleSheet(_fromUtf8("background-color: rgb(60, 96, 255);\n"
"color: rgb(255, 255, 255);"))
        self.switch_2.setIconSize(QtCore.QSize(64, 64))
        self.switch_2.setObjectName(_fromUtf8("switch_2"))
        self.gridLayout_B2.addWidget(self.switch_2, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(470, 20, 91, 91))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_R3 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_R3.setObjectName(_fromUtf8("gridLayout_R3"))
        self.rencoder_3 = QtGui.QDial(self.gridLayoutWidget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 229, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.rencoder_3.setPalette(palette)
        self.rencoder_3.setStyleSheet(_fromUtf8("background-color: rgb(185, 12, 15)"))
        self.rencoder_3.setMaximum(127)
        self.rencoder_3.setWrapping(True)
        self.rencoder_3.setObjectName(_fromUtf8("rencoder_3"))
        self.gridLayout_R3.addWidget(self.rencoder_3, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(470, 260, 99, 36))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_B4 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_B4.setObjectName(_fromUtf8("gridLayout_B4"))
        self.switch_4 = QtGui.QPushButton(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_4.sizePolicy().hasHeightForWidth())
        self.switch_4.setSizePolicy(sizePolicy)
        self.switch_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.switch_4.setFont(font)
        self.switch_4.setStyleSheet(_fromUtf8("background-color: rgb(60, 96, 255);\n"
"color: rgb(255, 255, 255);"))
        self.switch_4.setIconSize(QtCore.QSize(64, 64))
        self.switch_4.setObjectName(_fromUtf8("switch_4"))
        self.gridLayout_B4.addWidget(self.switch_4, 0, 0, 1, 1)
        self.gridLayoutWidget_9 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(470, 120, 95, 36))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_B3 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_B3.setObjectName(_fromUtf8("gridLayout_B3"))
        self.switch_3 = QtGui.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_3.sizePolicy().hasHeightForWidth())
        self.switch_3.setSizePolicy(sizePolicy)
        self.switch_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.switch_3.setFont(font)
        self.switch_3.setStyleSheet(_fromUtf8("background-color: rgb(60, 96, 255);\n"
"color: rgb(255, 255, 255);"))
        self.switch_3.setIconSize(QtCore.QSize(64, 64))
        self.switch_3.setObjectName(_fromUtf8("switch_3"))
        self.gridLayout_B3.addWidget(self.switch_3, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(ZynthianEmubox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(470, 160, 91, 91))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_R4 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_R4.setObjectName(_fromUtf8("gridLayout_R4"))
        self.rencoder_4 = QtGui.QDial(self.gridLayoutWidget_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 229, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.rencoder_4.setPalette(palette)
        self.rencoder_4.setStyleSheet(_fromUtf8("background-color: rgb(185, 12, 15)"))
        self.rencoder_4.setMaximum(127)
        self.rencoder_4.setWrapping(True)
        self.rencoder_4.setObjectName(_fromUtf8("rencoder_4"))
        self.gridLayout_R4.addWidget(self.rencoder_4, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(ZynthianEmubox)
        self.widget.setGeometry(QtCore.QRect(170, 0, 231, 41))
        self.widget.setStyleSheet(_fromUtf8("image: url(:/logo/img/zynthian_logo_black.png);"))
        self.widget.setObjectName(_fromUtf8("widget"))

        self.retranslateUi(ZynthianEmubox)
        QtCore.QMetaObject.connectSlotsByName(ZynthianEmubox)

    def retranslateUi(self, ZynthianEmubox):
        ZynthianEmubox.setWindowTitle(_translate("ZynthianEmubox", "Form", None))
        self.switch_1.setText(_translate("ZynthianEmubox", "1 / CH", None))
        self.switch_2.setText(_translate("ZynthianEmubox", "2 / BACK", None))
        self.switch_4.setText(_translate("ZynthianEmubox", "4 / SELECT", None))
        self.switch_3.setText(_translate("ZynthianEmubox", "3 / LS", None))

import zynthian_emuface_rc
